POST http://localhost:3000/api/accounts/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "username": "kxrim",
  "email": "test@gmail.com",
  "password": "Test1234"
}

###

POST http://localhost:3000/api/accounts/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "username": "kxrim",
  "email": "test@gmail.com",
  "password": "Test12534"
}
