@startuml

entity "User" {
  id : integer <<PK>>
  name : string
  email : string
  password : string
  profilePicture : string
}

entity "Friend" {
}

entity "Notification" {
  type : string
  content : string
  isRead : boolean
}

entity "Recipe" {
  id : integer <<PK>>
  name : string
  image : string
}

entity "CalenderEntry" {
  date : datetime
}

entity "FavoriteFood" {
}

User ||--o{ CalenderEntry
Recipe ||--o{ CalenderEntry

User ||--o{ FavoriteFood
Recipe ||--o{ FavoriteFood

User ||--o{ Notification

User ||--o{ Friend : has friend
User ||--o{ Friend : is friend

@enduml